//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportClube
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubePaye
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public Nullable<long> Date { get; set; }
        public Nullable<long> Price { get; set; }
        public Nullable<long> Pardakhti { get; set; }
        public string NumberFactor { get; set; }
        public string Picture { get; set; }
    }
}
