//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportClube
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public long Id { get; set; }
        public string Eshterak { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Tel { get; set; }
        public Nullable<long> Date { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public Nullable<long> BirthDay { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public string Picture { get; set; }
    }
}
