//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportClube
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportClubeEntities : DbContext
    {
        public SportClubeEntities()
            : base("name=SportClubeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClubePaye> ClubePaye { get; set; }
        public virtual DbSet<Coach> Coach { get; set; }
        public virtual DbSet<Place> Place { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Train> Train { get; set; }
        public virtual DbSet<TypePey> TypePey { get; set; }
        public virtual DbSet<TypeService> TypeService { get; set; }
    }
}
