//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportClube
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public long Id { get; set; }
        public string Eshterak { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string NameService { get; set; }
        public string TypeService { get; set; }
        public Nullable<long> DateService { get; set; }
        public Nullable<long> Bestankar { get; set; }
        public Nullable<long> Bedehkar { get; set; }
        public Nullable<long> Pardakhti { get; set; }
        public string TypePey { get; set; }
        public string TypeUser { get; set; }
    }
}
