//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportClube
{
    using System;
    using System.Collections.Generic;
    
    public partial class Train
    {
        public long C_Id { get; set; }
        public string TypeTrain { get; set; }
        public string CoachName { get; set; }
        public string PlayerName { get; set; }
        public Nullable<long> DateTrain { get; set; }
        public Nullable<long> TimeTrain { get; set; }
        public string C_Place { get; set; }
        public string Description { get; set; }
    }
}
