//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportClube
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeService
    {
        public long Id { get; set; }
        public string NameService { get; set; }
        public Nullable<long> PriceService { get; set; }
        public string TypeService1 { get; set; }
    }
}
